"""empty message

Revision ID: 0f9af55ad8d9
Revises: f2fe1522d2ef
Create Date: 2026-03-04 20:43:27.033495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9af55ad8d9'
down_revision = 'f2fe1522d2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
